apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: sjhong
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30082
